[package]
name = "leani-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures.workspace = true
leani-primitives = { path = "../primitives" }
leani-processor-api = { path = "../processor-api" }
leani-source-api = { path = "../source-api" }
leani-store-artifacts = { path = "../store-artifacts" }
leani-store-sqlite = { path = "../store-sqlite" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
axum.workspace = true
leani-api = { path = "../api" }
leani-processor-blobs = { path = "../processor-blobs" }
leani-testkit = { path = "../testkit" }
tempfile.workspace = true
tower.workspace = true

[lints]
workspace = true
