[package]
name = "leani-source-xatu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
leani-primitives = { path = "../primitives" }
leani-source-api = { path = "../source-api" }
object_store.workspace = true
parquet.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true

[lints]
workspace = true
