[package]
name = "leani-store-history"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
async-trait.workspace = true
blake3.workspace = true
flate2.workspace = true
futures.workspace = true
hex.workspace = true
leani-primitives = { path = "../primitives" }
leani-source-api = { path = "../source-api" }
postcard.workspace = true
serde.workspace = true
snap.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
leani-testkit = { path = "../testkit" }
tempfile.workspace = true

[lints]
workspace = true
