[package]
name = "leani-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
alloy-primitives.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
blake3.workspace = true
futures.workspace = true
flate2.workspace = true
hex.workspace = true
leani-primitives = { path = "../primitives" }
leani-processor-api = { path = "../processor-api" }
leani-processor-blobs = { path = "../processor-blobs" }
leani-processor-erc20 = { path = "../processor-erc20" }
leani-processor-uniswap = { path = "../processor-uniswap" }
leani-source-api = { path = "../source-api" }
leani-store-history = { path = "../store-history" }
leani-store-sqlite = { path = "../store-sqlite" }
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
leani-testkit = { path = "../testkit" }
tempfile.workspace = true
tower.workspace = true

[lints]
workspace = true
